### ISSUE TITLE
Linkintegrity not working from Plone Site/Portal

### ISSUE THREAD

**Issue by ThibautBorn** [plone/Products.CMFPlone#3832]
### What I did:

Adding a link in the textfield of the Plone Site/Root to another object, and then deleting this referenced object. 

### What I expect to happen:

Link Integrity should warn users of any references to the to-be-deleted-object. 
Like this:
![object_link](https://github.com/plone/Products.CMFPlone/assets/43573065/febccf92-f3ef-4464-8da4-6169c3eb6c50)

### What actually happened:

When the reference is created in the plone site/root itself, there is no warning.

![root_link](https://github.com/plone/Products.CMFPlone/assets/43573065/7ffd7da2-260f-4139-b38b-2a9763339a1e)

### What version of Plone/ Addons I am using:

Plone 6.0.6 classic

**Comment by jaroel** [comment]
This should be resolved by https://github.com/plone/Products.CMFPlone/issues/3833

**Comment by ThibautBorn** [comment]
Tested but I could reproduce the bug in Plone 6.0.7

**Comment by rohnsha0** [comment]
was able to reproduce the same on Plone 6.1.0 (6107)

**Comment by rohnsha0** [comment]
also, adding to it,  `page` type is not getting detected however `news` are getting detected

**Comment by jensens** [comment]
Verified still present. handlers.py line 94 explicitly skips IPloneSiteRoot. Links from the site root are never tracked by linkintegrity.
