### ISSUE TITLE
1Log in1 Link Persists on 404 Pages Even After Logging In (Plone Classic UI)

### ISSUE THREAD

**Issue by rohnsha0** [plone/Products.CMFPlone#4096]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

On 404 pages in Plone Classic UI, the "Log in" button persists even after the user has logged in.

![Image](https://github.com/user-attachments/assets/6a75e4e5-6704-4d52-bf7e-6cc016c60692)

### What I did:

- Navigated to a non-existent page in Plone, triggering a 404 error page.
- Logged in to the Plone Classic UI.

However, when navigating to the site root, the user is `logged in` 

### What I expect to happen:

After logging in, the "Log in" button should change to reflect the authenticated state (e.g., display the username or a "Log out" option).

### What actually happened:

- Even after logging in, the "Log in" button persists on 404 pages in the Plone Classic UI.
- This may cause confusion as it appears that the user is not logged in.

### What version of Plone/ Addons I am using:

- Plone 6.1.0rc2.dev0 (6107)
- CMF 3.6
- Zope 5.12
- Python 3.11.11 (main, Dec 29 2024, 13:41:59) [GCC 14.2.1 20240910]
- PIL 11.0.0 (Pillow)
- WSGI: On
- Server: waitress 3.0.2

**Comment by rohnsha0** [comment]
> Per my comment, [#4094 (comment)](https://github.com/plone/Products.CMFPlone/pull/4094#issuecomment-2629297327), we should consider a redirect after login, either to the site root (my preference) or to the same 404 page.
> 
> After logging in, you can visit `/404`, and the `Login` link still displays, but should instead either be removed (my preference) or `Logout` displayed.

I agree with the given suggestion!

**Comment by petschki** [comment]
The redirection in the login view got fixed here https://github.com/plone/Products.CMFPlone/pull/4094 ...
When using the login "modal" there is one more issue with the modal options: #4100 

The persistend login link on "not found" pages is a complete different story, because this page template has no authentication information and therefore displays the "anon-tools" viewlet.

**Comment by rohnsha0** [comment]
> The persistend login link on "not found" pages is a complete different story, because this page template has no authentication information and therefore displays the "anon-tools" viewlet.

I understand. 
But my question is, how a user will userstand that the login is a success? as there is no feedback!

**Comment by rohnsha0** [comment]
> The persistend login link on "not found" pages is a complete different story, because this page template has no authentication information and therefore displays the "anon-tools" viewlet.

I understand.
But my question is, how a user will userstand that the login is a success? as there is no feedback!
However my question might be irrelevant, but just out of curiousity!

**Comment by jensens** [comment]
Verified still present. error_message.pt uses main_template which renders anontools viewlet. No auth-aware logic for the 404 case — 'Log in' always shown.

**Comment by jensens** [comment]
**Root cause analysis:**

This is not a template bug. The "Log in" link appears because Zope's authentication pipeline never runs on 404 errors. The traversal loop in `BaseRequest.traverse()` raises `NotFound` before reaching the authentication code (PAS `validate()`, `newSecurityManager()`). The security manager stays empty, so all viewlets see an anonymous user — even if valid credentials are present in the request.

Fixing the auth pipeline for error pages is complex and touches security-sensitive Zope core code.

**Alternative proposal:** Render 404 (and possibly other error pages) as a simplified page without the full Plone chrome (no toolbar, viewlets, portlets). Just a styled error message with a link to the navigation root. This avoids the auth problem entirely and is arguably the better UX anyway — error pages shouldn't pretend to be full Plone pages with a half-broken security context.
