### ISSUE TITLE
Unlink display of the author's display date.

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.CMFPlone#668]
Today when the ['Allow anyone to view' about 'information'](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py#L888) field is selected in controlpanel, Plone displays both the [date as author](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/document_byline.pt#L2) of the content. Our suggestion is to unlink this behavior, so it can display only the date or just author.

**Comment by hvelarde** [comment]
:+1: I've seen this requirement before.

**Comment by davilima6** [comment]
Isn't it enough just having a wrappper around each information so it can be hidden with CSS? Remember: "Checkboxes kill your product" http://limi.net/checkboxes-that-kill/

**Comment by hvelarde** [comment]
@davilima6 not all check boxes kill you product; these ones are harmless :-)

**Comment by davilima6** [comment]
Yeah, you're probably right. If more integrators have been seeing this requirement then I'm also +1 on it!

**Comment by vangheem** [comment]
In Plone 5, document by line is removed right now. See https://github.com/plone/plone.app.layout/commit/1b9920f98473e0ce307303ea809849ff4a7406f4#diff-ab8a3fa00ecf8b7912bed20e4cafc7aeL359

The reason is that it was oddly forced into the toolbar and it didn't make much sense so we merged a more simple modified date into the toolbar history button.

Perhaps we still want the old style document by line in plone 5? Someone should create a PR if that is the case because ever since the betas, it hasn't been around the way issue understands it.

Moreover, this is not going to be changed in Plone 4--it would only be a Plone 5 change. That being the case, I am going to close this ticket. Please open a new ticket and potentially a PR to add back in the old document by line functionality on Plone 5.

**Comment by davilima6** [comment]
I can't open the PR right now but I'm +1 to have byline functionality back. Many sites count on that, especially journalism and media related ones.

**Comment by djay** [comment]
-1

If its there by default it has to be themed, making the themers job harder for majority of sites that don’t need it. If a site theme needs it then you can easily add it back yourself via plugins like collective.listingview or by creating your own viewlet or just diazo.

**Comment by davilima6** [comment]
I see. Then +1 for leaving it at least as a "BBB" hidden viewlet in order to ease the migrators' path.

**Comment by hvelarde** [comment]
so, you decided to remove the document byline because it didn't fix in the new toolbar? guys this is the kind of decisions that drive me nuts, seriously: we are adding features that are not standard to the core and removing others that of course are.

who said majority of sites are not using this feature? did you make a poll? all of our sites use it!

please let's bring back the document byline viewlet and please let's have a broader discussion on these kind of decisions.

@idgserpro could you please help working on the PR based on your work on IDGB? if not, I'll ask @rodfersou, but it will take some time.

:cactus:

**Comment by rodfersou** [comment]
+1 on bring back document byline

**Comment by vangheem** [comment]
@hvelarde have you tried plone 5? Did you see how it was implemented? I think you'd understand if you had.

Weird to freak out about this now as it's been like this for 6 months or more.

**Comment by hvelarde** [comment]
@vangheem you know I have tested it and I always give feedback on all the things I dislike about it because I care.

since Plone 4.1 I decided not to use earlier versions on production deployments; sorry, but we have a very small team and very limited resources.

I will use Plone 5 when it's mature enough and a clear path for migrations (and for developing add-ons keeping 4.3 compatibility) is on place; right now neither of them are clear to me.

**Comment by agnogueira** [comment]
+1 to bring it back. 
Show date and author in content area is a very basic thing for sites like news portals, intranets, community websites and blogs.
Byline could be hidden by default, but i think we cant remove and loose a basic feature like that.

**Comment by hvelarde** [comment]
@djay check this out: https://twitter.com/hvelarde/status/622045162542383104

**Comment by davilima6** [comment]
+1 on @hvelarde I think I underestimated it when I said mostly news and media sites use byline. I believe all intranets consider this important to show at first glance information and also many gov sites want to display at least date (since a specific person's name is often contraindicated and can't be just hidden with CSS, hence @idgserpro's request).

@vangheem I understand you want to get P5 out but please understand that for many a sprint like this works like a call for not so core members to have a more detailed look at P5 and comment on details or many things that have been ready for a while but not so usable or stable like the Toolbar or Resources Registries. Or patterns or that non-elegant _authenticator thing is Folder Contents URLs. It's a last chance to express our need for a less annoying upgrade path or our concern that removing some a11n hooks may facilitate for other CMSs to claim Plone's position in Govs etc.

**Comment by vangheem** [comment]
The document by line hasn't been in the content for 1 year--I just checked with Ramon. Ever since Plone 5 was alpha.

_authenticator params in urls are necessary for security unfortunately. I was thinking about changing those toolbar urls dynamically using javascript to POST so we can have nice urls.

**Comment by davilima6** [comment]
+1 for byline to be back
+1 for post and cleaning up our ever so clean URLs

**Comment by djay** [comment]
Last modified is in there for logged in users.
<img width="166" alt="screen shot 2015-07-17 at 9 16 28 pm" src="https://cloud.githubusercontent.com/assets/41700/8749098/4dbe23e4-2cc9-11e5-9074-b78c44132114.png">
<img width="530" alt="screen shot 2015-07-17 at 9 16 47 pm" src="https://cloud.githubusercontent.com/assets/41700/8749099/4dc3092c-2cc9-11e5-9c2a-3ec8a5bc6523.png">
I think we can squeeze in the last owner in the toolbar if it's really needed but I don't think it is.

In terms of showing the last updated etc in a themed public view... I'm not really sure document byline is best way to do that since you will likely want to customise it. We show last publication date instead using https://github.com/collective/collective.listingviews. Do we should all the dates and other information about the content in case the themer wants to expose it, or do we give them tools to expose exactly what they want, and how they want it?

**Comment by davilima6** [comment]
Unfortunately we're not arguing about the needs of logged-in users but public info and Plone's approach to current version site owners.

**Comment by idgserpro** [comment]
+1 for keeping byline. This is thoroughly used in all news websites, specially government. A CMS should have this builtin.

**Comment by djay** [comment]
If plone 4 does currently allow the byline to be public (we've never had site that wants this), then it should continue to do so. But for logged in users it doesn't make sense to keep it when the toolbar already provides the same info. 
What we are trying to achieve is if you are logged in, the page looks exactly the same as if you are logged out (minus the toolbar). So all the themer has to worry about with regard to plone UI for logged in users is the toolbar, nothing else. 
So by that logic, the setting should be to have the byline should be on everyone or off completely.

**Comment by djay** [comment]
We have never every had a government site that wants to reveal who the content author is.

**Comment by davilima6** [comment]
@djay That's the original point of this issue: decouple when from who.

Regarding this info being present in the toolbar, this has just been changed, right? I like the looks and just noticed that it also tells whether the item is being edited (locked) but if I have to choose one place for native Last modification and possibly joined Author info, that would be somewhere anonymous could also see it.

**Comment by idgserpro** [comment]
Brazilian government uses it a lot. We're asking in this issue the possibility of decoupling both properties so those who don't want to show the author can still show the date.

If you really decide to remove the byline, don't forget to review if ```allow_anon_views_about``` from controlpanel is still needed (I haven't check the new toolbar code if it's used in there), and at least a BBB for the documentbyline review like @davilima6 suggested.

**Comment by djay** [comment]
-  "Allow anyone to view 'about' information" - setting is still there under site setup > security and currently doesn't work.

I think for backwards compatibility reasons it is might a good idea that you can show that byline publicly if your old site did.
But for a bunch of reasons the current settings are stupid and should go
- Have one setting under "site" which specified publication date, and another under security, neither of which is intuitive. Since the byline is now a theme only issue any setting related to it should be in under site setup > theme.
- checkboxes for theming are self defeating. We have a powerful theme editor that lets to add and remove stuff, we have portlets, and diazo and in the future, mosaic all to those what is and isn't on a page. Checkboxes are a poor way to do it. Plone 5 is meant to be backwards incompatible release. The byline has to go sometime because not all themes need it. It's easy to add back in using diazo and some python expressions. Why not get rid of it now since it has to go eventually?

**Comment by hvelarde** [comment]
@djay this is not for backwards compatibility, this is clearly a regression: all major CMS have a byline; we can provide an option to exclude it, but we need it back.

if current settings are stupid, we need to fix them, not to remove a widely used feature because we just don't know how to deal with it.

**Comment by davilima6** [comment]
As @hvelarde asked, where is the data supporting the claim that minority of site owners need it? I know this was born inside Barceloneta sprint iirc mostly "to reduce visual clutter and simplify markup" but maybe in this one case it's worth reviewing the decision.

Re: checkboxes, I agree it's not good they're spread but as least it makes sense when Site administrator considers the supported use cases. Also I disagree they belong to Theming: it's metadata like tags so if one wants to omit it disable the viewlet or, if case proves too frequent, keep controls in Site Setup. Problem is P4 supports the usecase of public facing sites with some privileged metadata for editors so unifying those settings means dropping support on part of our TTW power-user potentials. I'd keep it that way until more thought is given (maybe a new panel for metatag configuration? or just wait for mosaic?), but not drop "CMS commodity" feature because we still didn't get it how to best display its settings.

**Comment by vangheem** [comment]
@hvelarde I think everyone gets your point from the tweet, github comments and message to community.plone.org.

The change happened after a series of other changes where the by line didn't make sense anymore.

The real problem here is everyone's different idealogical goals and in-practice use-cases. I see merit to both sides.

That being said, seeing how the removal was never plip'd and it's controversial, please provide a PR and I'm sure there would be no one complaining about merging the PR.

It would be ideal for all those with use-cases that are important to them, to be involved on the framework team and working on core. Also testing new versions earlier than 1 year prior to changes being made would be helpful.

In any case, late is better than never. Thank you for the feedback and the upcoming PR.

**Comment by djay** [comment]
We aren't removing because we don't know how to deal with it. It is just simply that it is a theming feature, no longer needed to support the editor usecase. As a theming feature the themer requires flexibility, not a one size fits all byline.

Plone has a byline just like any major CMS.
Here is how you add it
Under "site setup > theming > advanced settings > parameter expressions" add
```
modified = context/modified
```

Go into your rules.xml and add
```
<insert-after theme="#content h1"><p>Last modified {$modified}</p>
```
Done. Powerful and flexible. 

One of the reasons we could never use the byline plone provided on our sites is there was no way to customise the date format. The above does that and using whatever wording the themer chooses. Displaying the fullname and email of the owner is equally easy. Displaying the last person to modify should also be possible. Displaying the manager of the person who last modified it, as taken from ActiveDirectory, also possible. 
Let's not dumb down what we have. Let's teach people to use it and give the themer the full control they deserve from a modern CMS.

**Comment by hvelarde** [comment]
@vangheem thank you! 

@djay no, a byline is not a theming feature but an editor and end user use case; as @davilima6 already said it's about metadata: byline includes information about the author of an item and the date it was published or modified; Plone's byline also includes information on history, editing status (locking), contributors and copyright; some of these features where moved to other places, but not all of them.

how can you say there was no way to customize the date format? that makes absolutely no sense, do you know z3c.jbot, just to mention one? do you know you can also do that via ZMI?

following your example we could argue that everything is a theme feature and remove the title or the description from the view just because it can be inserted using Diazo.

guys, please, next time before removing a feature from Plone first ask; just because one or two members of the framework team doesn't use a feature it doesn't mean that nobody else uses it; and just because one or two members of the framework team want something inside the core, that neither means it belongs there.

we have literally hundreds, if not thousands, of sites build on top of Plone in all levels and branches of the Brazilian government; we need to know what's going on.

I will try to see if someone can join the framework team as I can't follow the whole stuff because of the reasons stated above.

**Comment by davilima6** [comment]
There is the themer, who allegedly shouldn't need to learn xslt or variables to accomplish simple tasks, and there's the site admin, that power user we all were in our first weeks with Plone, unaware of ZPT and Dublin Core but able to display and hide Plone bits by navigating through checkboxes. I know they often overlap but conceptually I think byline should remain as a Site admin configuration and not a themer task.

**Comment by bloodbare** [comment]
As on 27th of May 2014 we published a design of the toolbar (http://plone5ui.blogspot.nl/2014/05/week1-toolbar-concepts-redesigned.html) with the document by line there, and was not regrets, we also ended mails to plone developer mailing lists we implemented like that. It does not make sense to maintain to document by line. This week at see that that overlay was not so useful for more people it was moved to a browser view. 

As @vangheem said I'm agree that PR for adding a viewlet configurable throw the control panel to show it or not is welcome!

**Comment by djay** [comment]
@hvelarde Every single thing you mentioned is visible to the logged in user via the toolbar. 
So the issue is about the themed public view only. You can argue it should be simple. But already you are trying to make it more complicated by having extra checkboxes for if you display the author, or the modification date or the publishing date. As already stated power users will be catered for better in the future. For now lets not clutter the settings with more checkboxes which are only are halfarsed solution.

**Comment by hvelarde** [comment]
@bloodbare is not the toolbar we are talking about here.

@djay and every single thing I mentioned is not visible to the logged out user; and that should be visible without having to theme a site because it makes sense and was the way it was working since the beginning of times and nobody is expecting that to change.

**Comment by djay** [comment]
rather than champion one solution over another I tried to sum up the pros and cons of the real user problem in #741

**Comment by mactrash** [comment]
Please bring it back, now I read many plone site and don't know is that the article is fresh or old.

**Comment by hvelarde** [comment]
I have reopened this as a new issue.
